backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "ideas"
    label: "Ideas"
    folder: "src/pages/ideas"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Status", name: "status", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Type", name: "type", widget: "select", options: ["New idea/question", "Early dataset", "Observation"]}
      - {label: "Featured Project", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Image", name: "featuredimage", widget: image, required: false}
      - {label: "Dataset", name: "dataset", widget: string, required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "How to collaborate", name: "contact", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Description", name: "body", widget: "markdown"}
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-page"}
      - {label: Title, name: title, widget: string}
      - {label: Goals, name: goals, widget: object,
          fields: [{label: High Level Goals, name: high level, widget: string}, {label: SMART goals, name: smart goals, widget: text}]
      }
      - {label: Roles and Responsibilities, name: roles, widget: object, 
          fields: [
            {label: Scientific Lead, name: scientific lead, widget: string}, 
            {label: Scientific Project Lead, name: scientific project lead, widget: text},
            {label: Team Ambassadors, name: team ambassadors, widget: text},
            {label: Project Managers, name: project managers, widget: text}
            ]
      }
      - {label: Working groups, name: groups, widget: object,
          fields: [
            {label: Launch Material, name: launch material, widget: string}, 
            {label: Weekly working groups, name: weekly working groups, widget: text},
            {label: Team Ambassadors, name: team ambassadors, widget: text},
            {label: Agenda for next working group meeting, name: agenda, widget: text},
            {label: Working groups presentations and summaries, name: summaries, widget: text},
            ]
      }
      - {label: Current datasets, name: datasets, widget: string}
      - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
      - {label: Legend, name: body, widget: markdown}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Legend, name: body, widget: markdown}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
